code --install-extension adpyke.codesnap
code --install-extension Atishay-Jain.All-Autocomplete
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension nhoizey.gremlins
code --install-extension Prisma.prisma
code --install-extension silvenon.mdx
code --install-extension svelte.svelte-vscode
code --install-extension ziyasal.vscode-open-in-github
code --install-extension znck.grammarly
code --install-extension octref.vetur@0.34.1
code --install-extension teabyii.ayu@0.20.2
code --install-extension usernamehw.errorlens
